name: Scan Trivy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Docker image
        run: docker build -t demo:latest .

      # Download HTML template
      - name: Download Trivy HTML template
        run: |
          curl -sSL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -o html.tpl

      # Run Trivy scan in HTML format
      - name: Run Trivy scan (HTML)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'demo:latest'
          format: 'template'
          template: '@html.tpl'
          output: 'trivy-report.html'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          scanners: 'vuln'

      # Upload HTML report as artifact
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-html-report
          path: trivy-report.html
